Apps/tareas/urls.py
from django.conf.urls import url, include

''' Importa todas las vistas a utilizar desde el views.py, es decir todas las funciones que se encuentran en ella  '''

from Apps.tareas.views import index, tareas_view, tareas_lista_view, tareas_aprobar


''' Establecemos todas las urls disponibles para la Apps Tareas  '''

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^nueva_tarea$', tareas_view, name='nombre_tareas_form'),
    url(r'^listar_tareas$', tareas_lista_view, name='nombre_tareas_listar'),
    url(r'^aprobar_tareas/(?P<id_tarea>\d+)/$', tareas_aprobar, name='nombre_aprobar_tareas'),
]

Miniproyecto/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Apps.tareas.urls', namespace="tareas")),
    url(r'^tareas/', include('Apps.tareas.urls', namespace="tareas")),
]

Apps/tareas/models.py
from django.db import models

# Create your models here.


''' Creamos el model de tareas para el uso en el sitio y su creacion de BD de Postgresql  '''

class i00t_tareas(models.Model):
	co_estatus = models.IntegerField(default=1)
	nb_tarea = models.CharField(max_length=50)
	tx_descripcion = models.CharField(max_length=200)
	in_activo = models.IntegerField(default=1)

Apps/usuarios/models.py
from django.db import models

# Create your models here.

Apps/tareas/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse

''' Importa los datos del formulario desde App.tareas.form.py '''

from Apps.tareas.form import TareasForm

''' Importa el modelo de datos desde el models.py, que este caso es i00_tareas '''

from Apps.tareas.models import i00t_tareas

# Create your views here.


''' Carga de forma predeteminada el index.html del sitio '''

def index(request):
	return render(request, 'tareas/index.html')


''' Funcion que permite registrar una nueva tarea, solicitando a traves de TareaForm, que fue la carga del
model importado, los campos necesarios para realizar el registro de una nueva tarea'''

def tareas_view(request):
	if request.method == 'POST':
		form = TareasForm(request.POST)
		if form.is_valid():
			form.save()
		return redirect('tareas:nombre_tareas_listar')
	else:
		form = TareasForm()
	return render(request, 'tareas/tareas_form.html', {'form':form})


''' Funcion que permite la carga de la vista de todas las tareas registradas por el usuario '''

def tareas_lista_view(request):
	tareas = i00t_tareas.objects.all()
	data = {'lista_tareas':tareas}
	return render(request, 'tareas/listar_tareas.html', data)


''' La siguiente funcion aprueba una tarea, cargando la identificacion de la tarea por medio del id, se establecera de la siguiente manera:

co_estatus = 1: indica que la tarea es nueva y esta pendiente.
co_estatus = 2: indica que la tarea ya ha sido aprobada.

En esta funcion el co_estatus se establece en co_estatus = 2, como podemos observar en la linea de codigo Nro 54
'''

def tareas_aprobar(request, id_tarea):
	query = i00t_tareas.objects.get(id=id_tarea)
	if request.method == 'POST':
		co_estatus = '2';
		query.co_estatus = co_estatus
		query.save()
		return redirect('tareas:nombre_tareas_listar')
	return render(request, 'tareas/tareas_aprobar.html', {'info_tarea':query})

Apps/usuarios/views.py
from django.shortcuts import render

# Create your views here.

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'bootstrap-4.0.0/css/bootstrap.min.css' %}">
	<meta charset="utf-8">
	<title>{% block title %} Mini proyecto Tareas {% endblock %}</title>
</head>

  <body class="d-flex flex-column h-100">
    <header>
  <!-- Fixed navbar -->
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Mini proyecto</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Administracion de Django </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tareas:nombre_tareas_listar' %}">Tareas </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'tareas:nombre_tareas_form' %}">Nueva Tarea </a>
        </li>
      </ul>
    </div>
  </nav>
</header>


<main role="main" class="flex-shrink-0" style="margin-top:2%">
  <div class="container">

  	{% block content %}
    <h4 class="mt-5">Bievenido a miniproyecto de prueba</h4>
    <p class="lead">Bienvenido al miniproyecto de prueba realizado por Isaac Betancourt.</p>
    <p>Relizado bajo las tecnologías:</p>

    <ul>
		<li>Framework:  <code>Django</code> </li>
		<li>Lenguajes: <code>Python 3.5</code> </li>
		<li>Base de datos: <code>Postgresql</code> </li>
		<li>Plantilla de diseño: <code>Bootstrap 4.0</code></li>
	</ul>
    
   {% endblock %}
  </div>
</main>




<footer class="footer mt-auto py-3">
  <div class="container">
    <span class="text-muted">Miniaplicación realizada bajo el framework de Django sin usa de javascript,
	solo se utilizó el puro manejador y recursos de Django para esta prueba.</span>
  </div>
</footer>


</body>
</html>

<script src="{% static 'jquery/jquery-1.11.2.min.js'%}"></script>
<script src="{% static 'bootstrap-4.0.0/js/bootstrap.min.js'%}"></script>

templates/tareas/index.html
{% extends 'base/base.html' %}

templates/tareas/listar_tareas.html
{% extends 'base/base.html' %}

{% block content %}
 	<h4 class="mt-5">Lista de todas las tareas actuales y su estatus</h4>
{% if lista_tareas %}
<table class="table table-bordered table-hover table-sm" width="100%">
	<thead class="thead-dark">
	<tr>
		<th width="40%">Tareas</th>
		<th width="30%">Descripción</th>
		<th width="20%">Estatus</th>
		<th width="10%">Acciones</th>
	</tr>
	</thead>
	<tbody>
		{% for row in lista_tareas %}
		<tr>
			<td>{{ row.nb_tarea }}</td>
			<td>{{ row.tx_descripcion }}</td>
			{% if row.co_estatus == 1 %}
			<td><label class="text text-info">Pendiente</label></td>
			{% else %}
			<td><label class="text text-success">Aprobado</label></td>
			{% endif %}
			{% if row.co_estatus == 1 %}
			<td><a href="{% url 'tareas:nombre_aprobar_tareas' row.id%}" class="btn btn-success">Aprobar</a></td>
			{% endif %}

		</tr>
		{% endfor %}

	</tbody>

</table>
{% else %}

		<h5>Sin registro de tareas</h5>

		{% endif %}



{% endblock %}

templates/tareas/tareas_aprobar.html
{% extends 'base/base.html' %}

{% block content %}

	<h4 class="mt-5">Aprobar tarea</h4>

	<form method="post">
		{% csrf_token %}
		<h6>¿Desea aprobar esta tarea {{ info_tarea.nb_tarea }}?</h6>

		<button type="submit" class="btn btn-success">Si, Aprobar</button>
		<a class="btn default" href="{% url 'tareas:nombre_tareas_listar' %}">No, cancelar</a>	
	</form>


{% endblock %}

templates/tareas/tareas_form.html
{% extends 'base/base.html' %}

{% block content %}
 	<h4 class="mt-5">Nueva tarea</h4>

	<div class="row">
		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 ">
			<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-primary">Agregar</button>	

			</form>
		</div>
	</div>

{% endblock %}